name: mpia
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=3.3.0 <4.0.0"

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.6
    get: ^4.6.6
    equatable: ^2.0.5
    json_annotation: ^4.8.1
    retrofit: ^4.0.3
    dio: ^5.4.1
    infinite_scroll_pagination: ^4.0.0
    cached_network_image: ^3.3.1
    dartz: ^0.10.1
    get_it: ^7.6.7
    flex_color_scheme: ^7.3.1
    google_fonts: ^6.1.0
    webview_flutter: ^4.5.0
    pretty_dio_logger: ^1.3.1
    syncfusion_flutter_datepicker: ^24.2.6
    syncfusion_flutter_charts: ^24.2.6
    get_storage: ^2.1.1
    flutter_easyloading: ^3.0.5
    datetime_setting: ^2.0.2
    tflite_flutter: ^0.9.0
    camera: ^0.9.4+19
    path_provider: ^2.0.9
    path: ^1.8.0
    google_ml_kit: ^0.13.0
    image: ^4.1.7

flutter_gen:
    output: lib/gen/
    line_length: 80
    assets:
        outputs:
            package_parameter_enabled: true

dev_dependencies:
    build_runner: ^2.4.8
    flutter_gen_runner: ^5.4.0
    flutter_launcher_icons: ^0.13.1
    flutter_lints: ^2.0.0
    flutter_test:
        sdk: flutter
    hive_generator: ^2.0.1
    json_serializable: ^6.7.1
    retrofit_generator: ^8.0.6
    freezed: ^2.3.4
    flutter_flavorizr: ^2.2.2

flutter:
    uses-material-design: true
    assets:
        - assets/icons/
        - assets/images/
        - assets/others/
